application: schpeyeder-web
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /scripts
  static_dir: scripts
  
- url: /js
  static_dir: js
  
- url: /lib
  static_dir: lib
  
- url: /css
  static_dir: css

- url: /partials
  static_dir: partials
  
- url: /.*
  script: main.application
  
libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest